---
- name: apply common configuration to all nodes
  hosts: all
  become: true
  remote_user: root
  vars:
    document_root: /vagrant
  handlers:
    - name: reload apache
      service: name=apache2 state=reloaded
  tasks:
    - name: update apt cache
      apt: update_cache=yes
    - name: install python3
      apt: name=python3 state=present
    - include: tasks/apache.yml
    - include: tasks/mosquitto.yml
    - include: tasks/photoframe.yml
#    - include: tasks/mysql.yml
#    - include: tasks/php.yml
