Vagrant.configure('2') do |config|

  config.vm.define "lin_sys_3" do |config|
      config.vm.provider :linode do |provider, override|
        override.nfs.functional = false
        override.ssh.username = 'vagrant'
        override.ssh.private_key_path = '~/.ssh/id_rsa'

        override.vm.box = 'linode'
        override.vm.box_url = "https://github.com/displague/vagrant-linode/raw/master/box/linode.box"
        provider.token = ENV['LINODE_TOKEN']

        #Linode Settings
        provider.distribution = 'Debian 8'
        provider.datacenter = 'fremont'
        provider.plan = '1024'
        provider.label = 'sys3-deb-8'

      end
      config.vm.network "forwarded_port", guest: 80, host: 14280

      config.vm.provision :ansible do |ansible|
        ansible.playbook = "../playbook.yml"
      end
  end
end
