Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"

  config.vm.synced_folder "./", "/vagrant"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.name = "vbox-pf-mqtt"
  end

  config.vm.network "forwarded_port", guest: 80, host: 14280
  
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "../playbook.yml"
  end
end
