Vagrant.configure('2') do |config|

  config.vm.define "system3" do |config|
      config.vm.provider :digital_ocean do |provider, override|
        override.nfs.functional = false
        override.ssh.username = 'vagrant'
        override.ssh.private_key_path = '~/.ssh/id_rsa'
        override.vm.box = 'digital_ocean'
        override.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
        provider.token = ENV['DIGITALOCEAN_TOKEN']
        provider.image = 'debian-8-x64'
        provider.region = 'sfo1'
        provider.size = '512mb'

      end
      config.vm.network "forwarded_port", guest: 80, host: 14280

      config.vm.provision :ansible do |ansible|
        ansible.playbook = "../playbook.yml"
      end
  end
end
