- hosts: all
  become: true
  user: pi

  roles:
    - role: raspbian_bootstrap
      dbs_apt_default_host: "mirrordirector.raspbian.org"
      ansible_ssh_private_key_file: "keys/rpi_rsa"
      dbs_ssh_pubkey: "{{ lookup('file', 'keys/rpi_rsa.pub') }}"
    - role: nerab.rsyslog-patch
    - role: firewall
      open_ports: ["ssh"]
    - role: mikolak.raspi-config
      raspi_config_update_packages: no
    - role: grumpydog.photoframe

#  vars:
#    raspi_config_update_packages: no
#    open_ports:
#      - "ssh"

  vars_prompt:
    - name: "password"
      prompt: "Enter new password for user pi"
      private: yes
